version: '3'

services:
  project_redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass secret

  project_rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  project_postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
    ports:
      - 5432:5432
