export enum UserDomainExceptionEnum {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_EMAIL_ADDRESS = 'INVALID_EMAIL_ADDRESS',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
