export enum ExceptionEnum {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND_EXCEPTION = 'NOT_FOUND_EXCEPTION',
  INFRASTRUCTURE_EXCEPTION = 'INFRASTRUCTURE_EXCEPTION',
  INVALID_GUID_FORMAT = 'INVALID_GUID_FORMAT',
}
