export enum AppConfigEnum {
  NODE_ENV = 'NODE_ENV',
  SERVER_CONFIG = 'SERVER_CONFIG',
  POSTGRESQL_CONFIG = 'POSTGRESQL_CONFIG',
  JWT_CONFIG = 'JWT_CONFIG',
  RABBITMQ_CONFIG = 'RABBITMQ_CONFIG',
  MONGO_CONFIG = 'MONGO_CONFIG',
  REDIS_CONFIG = 'REDIS_CONFIG',
}
